#############################################################################
# Makefile for building: ImageSpider
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  ImageSpider.pro
# Template: subdirs
# Command: D:\Qt\Qt5.5.1\5.5\msvc2013\bin\qmake.exe -spec win32-msvc2013 -o Makefile ImageSpider.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = D:\Qt\Qt5.5.1\5.5\msvc2013\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-SpiderUi \
		sub-Spider


sub-SpiderUi-qmake_all:  FORCE
	@if not exist SpiderUi\ mkdir SpiderUi\ & if not exist SpiderUi\ exit 1
	cd SpiderUi\ && $(QMAKE) D:\Qt\Projects\ImageSpider\SpiderUi\SpiderUi.pro -spec win32-msvc2013 -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SpiderUi\ && $(MAKE) -f Makefile qmake_all
sub-SpiderUi: FORCE
	@if not exist SpiderUi\ mkdir SpiderUi\ & if not exist SpiderUi\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SpiderUi\ && ( if not exist Makefile $(QMAKE) D:\Qt\Projects\ImageSpider\SpiderUi\SpiderUi.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile
sub-SpiderUi-make_first: FORCE
	@if not exist SpiderUi\ mkdir SpiderUi\ & if not exist SpiderUi\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SpiderUi\ && ( if not exist Makefile $(QMAKE) D:\Qt\Projects\ImageSpider\SpiderUi\SpiderUi.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile 
sub-SpiderUi-all: FORCE
	@if not exist SpiderUi\ mkdir SpiderUi\ & if not exist SpiderUi\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SpiderUi\ && ( if not exist Makefile $(QMAKE) D:\Qt\Projects\ImageSpider\SpiderUi\SpiderUi.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile all
sub-SpiderUi-clean: FORCE
	@if not exist SpiderUi\ mkdir SpiderUi\ & if not exist SpiderUi\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SpiderUi\ && ( if not exist Makefile $(QMAKE) D:\Qt\Projects\ImageSpider\SpiderUi\SpiderUi.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile clean
sub-SpiderUi-distclean: FORCE
	@if not exist SpiderUi\ mkdir SpiderUi\ & if not exist SpiderUi\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SpiderUi\ && ( if not exist Makefile $(QMAKE) D:\Qt\Projects\ImageSpider\SpiderUi\SpiderUi.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile distclean
sub-SpiderUi-install_subtargets: FORCE
	@if not exist SpiderUi\ mkdir SpiderUi\ & if not exist SpiderUi\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SpiderUi\ && ( if not exist Makefile $(QMAKE) D:\Qt\Projects\ImageSpider\SpiderUi\SpiderUi.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile install
sub-SpiderUi-uninstall_subtargets: FORCE
	@if not exist SpiderUi\ mkdir SpiderUi\ & if not exist SpiderUi\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SpiderUi\ && ( if not exist Makefile $(QMAKE) D:\Qt\Projects\ImageSpider\SpiderUi\SpiderUi.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-Spider-qmake_all:  FORCE
	@if not exist Spider\ mkdir Spider\ & if not exist Spider\ exit 1
	cd Spider\ && $(QMAKE) D:\Qt\Projects\ImageSpider\Spider\Spider.pro -spec win32-msvc2013 -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Spider\ && $(MAKE) -f Makefile qmake_all
sub-Spider: FORCE
	@if not exist Spider\ mkdir Spider\ & if not exist Spider\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Spider\ && ( if not exist Makefile $(QMAKE) D:\Qt\Projects\ImageSpider\Spider\Spider.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile
sub-Spider-make_first: FORCE
	@if not exist Spider\ mkdir Spider\ & if not exist Spider\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Spider\ && ( if not exist Makefile $(QMAKE) D:\Qt\Projects\ImageSpider\Spider\Spider.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile 
sub-Spider-all: FORCE
	@if not exist Spider\ mkdir Spider\ & if not exist Spider\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Spider\ && ( if not exist Makefile $(QMAKE) D:\Qt\Projects\ImageSpider\Spider\Spider.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile all
sub-Spider-clean: FORCE
	@if not exist Spider\ mkdir Spider\ & if not exist Spider\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Spider\ && ( if not exist Makefile $(QMAKE) D:\Qt\Projects\ImageSpider\Spider\Spider.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile clean
sub-Spider-distclean: FORCE
	@if not exist Spider\ mkdir Spider\ & if not exist Spider\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Spider\ && ( if not exist Makefile $(QMAKE) D:\Qt\Projects\ImageSpider\Spider\Spider.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile distclean
sub-Spider-install_subtargets: FORCE
	@if not exist Spider\ mkdir Spider\ & if not exist Spider\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Spider\ && ( if not exist Makefile $(QMAKE) D:\Qt\Projects\ImageSpider\Spider\Spider.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile install
sub-Spider-uninstall_subtargets: FORCE
	@if not exist Spider\ mkdir Spider\ & if not exist Spider\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Spider\ && ( if not exist Makefile $(QMAKE) D:\Qt\Projects\ImageSpider\Spider\Spider.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: ImageSpider.pro ..\..\Qt5.5.1\5.5\msvc2013\mkspecs\win32-msvc2013\qmake.conf ..\..\Qt5.5.1\5.5\msvc2013\mkspecs\features\spec_pre.prf \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\common\msvc-desktop.conf \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\qconfig.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dcollision.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dcollision_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dcore.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dcore_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dinput.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dinput_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dlogic.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dlogic_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dquick.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dquick_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dquickrenderer.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dquickrenderer_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3drenderer.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3drenderer_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_axbase.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_axbase_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_axcontainer.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_axcontainer_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_axserver.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_axserver_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_bluetooth.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_bluetooth_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_bootstrap_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_clucene_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_concurrent.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_concurrent_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_core.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_core_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_dbus.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_dbus_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_declarative.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_declarative_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_designer.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_designer_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_designercomponents_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_enginio.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_enginio_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_gui.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_gui_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_help.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_help_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_location.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_location_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_multimedia.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_multimedia_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_multimediawidgets.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_network.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_network_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_nfc.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_nfc_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_opengl.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_opengl_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_openglextensions.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_openglextensions_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_platformsupport_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_positioning.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_positioning_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_printsupport.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_printsupport_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_qml.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_qml_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_qmltest.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_qmltest_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_quick.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_quick_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_quickparticles_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_quickwidgets.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_script.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_script_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_scripttools.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_scripttools_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_sensors.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_sensors_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_serialport.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_serialport_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_sql.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_sql_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_svg.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_svg_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_testlib.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_testlib_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_uiplugin.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_uitools.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_uitools_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webchannel.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webchannel_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webengine.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webengine_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webenginecore.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webenginecore_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webenginewidgets.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webenginewidgets_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webkit.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webkit_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webkitwidgets.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webkitwidgets_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_websockets.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_websockets_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webview_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_widgets.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_widgets_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_winextras.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_winextras_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_xml.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_xml_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_xmlpatterns.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\features\qt_functions.prf \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\features\qt_config.prf \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\features\win32\qt_config.prf \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\win32-msvc2013\qmake.conf \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\features\spec_post.prf \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\features\exclusive_builds.prf \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\features\default_pre.prf \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\features\win32\default_pre.prf \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\features\resolve_config.prf \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\features\exclusive_builds_post.prf \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\features\default_post.prf \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\features\win32\rtti.prf \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\features\c++11.prf \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\features\precompile_header.prf \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\features\warn_on.prf \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\features\win32\windows.prf \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\features\testcase_targets.prf \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\features\exceptions.prf \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\features\yacc.prf \
		..\..\Qt5.5.1\5.5\msvc2013\mkspecs\features\lex.prf \
		ImageSpider.pro
	$(QMAKE) -spec win32-msvc2013 -o Makefile ImageSpider.pro
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\features\spec_pre.prf:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\common\msvc-desktop.conf:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\qconfig.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dcollision.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dcollision_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dcore.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dcore_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dinput.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dinput_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dlogic.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dlogic_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dquick.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dquick_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dquickrenderer.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3dquickrenderer_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3drenderer.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_3drenderer_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_axbase.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_axbase_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_axcontainer.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_axcontainer_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_axserver.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_axserver_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_bluetooth.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_bluetooth_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_bootstrap_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_clucene_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_concurrent.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_concurrent_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_core.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_core_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_dbus.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_dbus_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_declarative.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_declarative_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_designer.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_designer_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_designercomponents_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_enginio.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_enginio_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_gui.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_gui_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_help.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_help_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_location.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_location_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_multimedia.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_multimedia_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_multimediawidgets.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_network.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_network_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_nfc.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_nfc_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_opengl.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_opengl_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_openglextensions.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_openglextensions_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_platformsupport_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_positioning.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_positioning_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_printsupport.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_printsupport_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_qml.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_qml_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_qmldevtools_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_qmltest.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_qmltest_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_quick.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_quick_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_quickparticles_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_quickwidgets.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_quickwidgets_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_script.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_script_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_scripttools.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_scripttools_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_sensors.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_sensors_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_serialport.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_serialport_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_sql.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_sql_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_svg.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_svg_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_testlib.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_testlib_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_uiplugin.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_uitools.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_uitools_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webchannel.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webchannel_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webengine.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webengine_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webenginecore.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webenginecore_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webenginewidgets.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webenginewidgets_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webkit.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webkit_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webkitwidgets.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webkitwidgets_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_websockets.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_websockets_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_webview_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_widgets.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_widgets_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_winextras.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_winextras_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_xml.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_xml_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_xmlpatterns.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\features\qt_functions.prf:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\features\qt_config.prf:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\features\win32\qt_config.prf:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\win32-msvc2013\qmake.conf:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\features\spec_post.prf:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\features\exclusive_builds.prf:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\features\default_pre.prf:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\features\win32\default_pre.prf:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\features\resolve_config.prf:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\features\exclusive_builds_post.prf:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\features\default_post.prf:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\features\win32\rtti.prf:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\features\c++11.prf:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\features\precompile_header.prf:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\features\warn_on.prf:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\features\win32\windows.prf:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\features\testcase_targets.prf:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\features\exceptions.prf:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\features\yacc.prf:
..\..\Qt5.5.1\5.5\msvc2013\mkspecs\features\lex.prf:
ImageSpider.pro:
qmake: FORCE
	@$(QMAKE) -spec win32-msvc2013 -o Makefile ImageSpider.pro

qmake_all: sub-SpiderUi-qmake_all sub-Spider-qmake_all FORCE

make_first: sub-SpiderUi-make_first sub-Spider-make_first  FORCE
all: sub-SpiderUi-all sub-Spider-all  FORCE
clean: sub-SpiderUi-clean sub-Spider-clean  FORCE
distclean: sub-SpiderUi-distclean sub-Spider-distclean  FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-SpiderUi-install_subtargets sub-Spider-install_subtargets FORCE
uninstall_subtargets: sub-SpiderUi-uninstall_subtargets sub-Spider-uninstall_subtargets FORCE

sub-SpiderUi-debug:
	@if not exist SpiderUi\ mkdir SpiderUi\ & if not exist SpiderUi\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SpiderUi\ && ( if not exist Makefile $(QMAKE) D:\Qt\Projects\ImageSpider\SpiderUi\SpiderUi.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile debug
sub-Spider-debug:
	@if not exist Spider\ mkdir Spider\ & if not exist Spider\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Spider\ && ( if not exist Makefile $(QMAKE) D:\Qt\Projects\ImageSpider\Spider\Spider.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile debug
debug: sub-SpiderUi-debug sub-Spider-debug

sub-SpiderUi-release:
	@if not exist SpiderUi\ mkdir SpiderUi\ & if not exist SpiderUi\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SpiderUi\ && ( if not exist Makefile $(QMAKE) D:\Qt\Projects\ImageSpider\SpiderUi\SpiderUi.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile release
sub-Spider-release:
	@if not exist Spider\ mkdir Spider\ & if not exist Spider\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Spider\ && ( if not exist Makefile $(QMAKE) D:\Qt\Projects\ImageSpider\Spider\Spider.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile release
release: sub-SpiderUi-release sub-Spider-release

sub-SpiderUi-check:
	@if not exist SpiderUi\ mkdir SpiderUi\ & if not exist SpiderUi\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd SpiderUi\ && ( if not exist Makefile $(QMAKE) D:\Qt\Projects\ImageSpider\SpiderUi\SpiderUi.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile check
sub-Spider-check:
	@if not exist Spider\ mkdir Spider\ & if not exist Spider\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd Spider\ && ( if not exist Makefile $(QMAKE) D:\Qt\Projects\ImageSpider\Spider\Spider.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile check
check: sub-SpiderUi-check sub-Spider-check
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

